### ISSUE TITLE
font issues

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-basemaps#21]
It looks like we have issues with fonts in some languages
https://tile.gbif.org/3857/omt/5/15/12@2x.png?style=gbif-natural
https://tile.gbif.org/3857/omt/5/15/12@2x.png?style=gbif-natural-zh

![12@2x](https://user-images.githubusercontent.com/6759267/175937130-01668f23-56c0-4b98-a532-2d3d8fe6262b.png)

**Comment by MattBlissett** [comment]
Also Inuktitut (Canadian aboriginal) script: ᑎᑎᕋᐅᓯᖅ ᓄᑖᖅ
