### ISSUE TITLE
Tasmania disappears from basemaps when you zoom in

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-basemaps#3]
Tasmania disappears from basemaps when you zoom in

![screen shot 2017-06-14 at 22 49 54](https://user-images.githubusercontent.com/6759267/27154027-df42d624-5153-11e7-8589-f3db16159006.png)
![screen shot 2017-06-14 at 22 49 50](https://user-images.githubusercontent.com/6759267/27154028-df44f062-5153-11e7-92b7-c37ce5189adf.png)

**Comment by MattBlissett** [comment]
Live view:

Zoom level 5:
![Z5](https://tile.gbif.org/4326/omt/5/58/23@1x.png?style=gbif-classic)

Zoom level 6:
![Z6](https://tile.gbif.org/4326/omt/6/116/46@1x.png?style=gbif-classic)

The island polygon is evidently broken.

**Comment by MattBlissett** [comment]
Fixed with regenerated 4326 projection base tiles.
