### ISSUE TITLE
nonse parameters change styling

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-basemaps#5]
i find that the baseman api is acting weird. take the noise param in the end here. that shouldn’t make a difference 

https://tile.gbif-dev.org/4326/omt/10/993/308@1x.png?style=gbif-light&srs=EPSG%3A4326&nonsense=5

https://tile.gbif-dev.org/4326/omt/10/993/308@1x.png?style=gbif-light&srs=EPSG%3A4326&nonsense=4

yet it result in different map styles.

I noticed because I just tried to bust cache for a test

**Comment by MattBlissett** [comment]
Underlying cause is #6.
